### ISSUE TITLE
Feature Request: Automated Photo Copying to External USB Device

### ISSUE THREAD

**Issue by Peda1996** [photobooth-app/photobooth-app#138]
The photobooth application currently allows users to take and store photos locally. However, there might be a need for immediate and easy transfer of these photos to an external storage device, like a USB stick.

### Feature Description:
I propose a feature that automatically detects the connection of an external USB device and copies all new photos (or photos that haven't been copied yet) to this device.

This could then be just run in another thread / daemon.

**Comment by mgineer85** [comment]
Currently there are 2 options
- QR code shareservice using single php script on the other side and
- Download zip in files tab in the backend.

I see it could be useful. Maybe use a simple Linux service? Wouldn’t work on windows though.

**Comment by Peda1996** [comment]
This is my take on it :)
https://github.com/photobooth-app/photobooth-app/pull/139

**Comment by mgineer85** [comment]
Slightly modified version is added to repo now. Thx for the pull request.
Will release a new version very soon.

**Comment by Peda1996** [comment]
Thanks for refactoring my code, and accepting this PR :)
