### ISSUE TITLE
GIF Creation Issue with Canon 2000D (gphoto2 backend)

### ISSUE THREAD

**Issue by Peda1996** [photobooth-app/photobooth-app#154]
When attempting to create GIFs with my Canon 2000D, the process does not work as expected. Instead of recording a live feed, the camera takes one photo and then merges it with another example photo.

# Steps to Reproduce:
1. Use the gphoto2 Backend
2. Capture photo using GIF mode.
3. Observe the output.

# Expected Behavior:
1. The camera should set focus. (go in viewfinder mode, set focus, and return to livefeed mode)
2. Then start recording the live feed (on the newly set focus).
3. Stop recording the live feed upon completion.

# Actual Behavior:
1. The camera takes one single photo.
2. This photo is then merged with another random photo, not creating a proper GIF.

Environment:
- Canon 2000D
- Operating System: Ubuntu

**Comment by mgineer85** [comment]
Actually the gif is implemented like that. You can set the number of captures and duration per image. Needs documentation and feature description 😌
Once gif feature is completed including postprocessing pipeline and performance is optimized I consider adding a video feature that records an actual video for some seconds.

**Comment by Peda1996** [comment]
Oh sorry, somehow i did fully miss that 😅.

Then it might be considerable to increase the number of default captures to 2, or more, to avoid confusion of new users^^.

**Comment by mgineer85** [comment]
Ah, yeah will change that.

**Comment by mgineer85** [comment]
Default is now 2 images to take for a GIF.
Also changed the last image to following one.

![photobooth-gif-animation-predefined-image](https://github.com/photobooth-app/photobooth-app/assets/3868450/e26e4123-a30c-491c-92e7-a6b0e9dac877)

Will take little time to release because there was much refactoring going on that needs to be tested first.
