### ISSUE TITLE
transparent background in pictures for collages

### ISSUE THREAD

**Issue by Paradoxa** [photobooth-app/photobooth-app#160]
**Is your feature request related to a problem? Please describe.**
Images that are loaded into the collage have a black background. This is annoying if the images in the collage overlap.

**Describe the solution you'd like**
I would like these to be transparent.

**Describe alternatives you've considered**
possible solution:

1. in file -> photobooth-app/photobooth/services/mediaprocessing/collage_pipelinestages.py
2. find line 31
3. change -> canvas.paste(_image, (_definition.pos_x - offset_x, _definition.pos_y - offset_y)) 
 to -> canvas.paste(_image, (_definition.pos_x - offset_x, _definition.pos_y - offset_y),**_image**)

**Additional context**

**Comment by mgineer85** [comment]
I'm not 100% sure what is happening to the image.
Is it possible to post a screenshot here showing the problem?

**Comment by mgineer85** [comment]
Version 1.2.1 is released including a fix. Thx for reporting!
