### ISSUE TITLE
Camera not working "Could not claim interface 0"

### ISSUE THREAD

**Issue by samyness** [photobooth-app/photobooth-app#166]
**Describe the bug**
Upon starting the Raspberry Pi with the camera enabled, the camera is not recognized. The error "Could not claim interface 0" is observed in the log files. It has been identified that the gvfs-gphoto2-volume-monitor process running in the background is the cause. The issue is resolved by terminating the processes gvfs-photo2-volume-monitor and gvfsd.gphoto2 --spawner :1.3 /org/gtk/gvfs/exec_spaw/21. The goal is to implement a solution where the script runs on startup and establishes a connection with the camera.

**To Reproduce**
1. Start the Raspberry Pi with the camera with CF-Card or SD-Card in it connected.
2. Observe the error message "Could not claim interface 0" in the log files.
3. Manually terminate the processes gvfs-photo2-volume-monitor and gvfsd.gphoto2 --spawner :1.3 /org/gtk/gvfs/exec_spaw/21.
4. Confirm that the issue is resolved.

**Expected behavior**
The camera should be recognized and no "Could not claim interface 0" error should occur on startup.

**Screenshots**
N/A

**System**
 - OS: Raspberry Pi Bookworm 64bit
 - Browser: N/A
 - Version: N/A

**Additional context**
If further information is needed, please feel free to ask.

**Comment by mgineer85** [comment]
Yes, please check this FAQ: https://photobooth-app.org/support/faq/#gphoto2-camera-found-but-no-access
I think that should help solving.

Will add a hint to the section in the gphoto2 camera setup chapter also, so it's easier to find.
