### ISSUE TITLE
Gphoto2 Disable Viewfinder Before Capture causes timeout receiving frames (abstractbackend.py:253)

### ISSUE THREAD

**Issue by samyness** [photobooth-app/photobooth-app#176]
**Describe the bug**
If I activate the Gphoto2 Disable Viewfinder Before Capture, I'm getting an "timeout receiving frames (abstractbackend.py:253)" error and the camera triggers two shots.

**To Reproduce**
activate Gphoto2 Disable viewfinder before capture with a D810 

**Expected behavior**
I expacted better Autofocus!

**Screenshots**

LOG attached!
[LOG.txt](https://github.com/photobooth-app/photobooth-app/files/14197196/LOG.txt)

**Comment by mgineer85** [comment]
Yeah, maybe the viewfinder disable is only good for canon and harmful for nikon?
How is the capture speed compared if you disable liveview to liveview enabled?
How are the absolute times?

**Comment by samyness** [comment]
I need to check the absolute times first. Just based on feeling, there's no difference. 

Do you know what triggers the second photo? Actually, taking the second photo is the only mistake. The correct, first capture is displayed and saved and the Camera focus is **much** better than with activ viewfinder.

**Comment by mgineer85** [comment]
Is it actually taking a second photo or maybe just the control sequence that sounds like it but no photo taken?

**Comment by samyness** [comment]
It takes a second Picture 6seconds later:
```
2024-02-07 18:02:26,479 [    INFO] taking hq picture (gphoto2.py:243)
2024-02-07 18:02:32,165 [    INFO] taking hq picture (gphoto2.py:243)
```

**Comment by samyness** [comment]
Should I try to set the Timeout receicing frames in gphoto.py to 10sec.? 

```
def _wait_for_hq_image(self):
        with self._hires_data.condition:
            self._hires_data.request_ready.set()
            if not self._hires_data.condition.wait(timeout=10):
                raise TimeoutError("timeout receiving frames")

        self._hires_data.request_ready.clear()
        return self._hires_data.data
```

**Comment by mgineer85** [comment]
That’s very Long. 
you can try but I prefer to find a way with shorter capture time.
It would be interesting if it’s faster with only jpeg capture.

**Comment by samyness** [comment]
Thats only jpeg capture, but in highest quality (35mb/picture).

**Comment by mgineer85** [comment]
Holy, ok, I think transfer time comes here to an reasonable amount. Also when switching to raw plus storing to the sd card it will take even longer until all is settled.

I think the modes used are not so reasonable for a PhotoBooth like this or might need heavy optimization. Processing the images afterwards might need some time also?

**Comment by samyness** [comment]
```
2024-02-07 18:02:32,995 [    INFO] -- process time: 1.59s to create scaled images (processingservice.py:237)
2024-02-07 18:02:33,355 [    INFO] -- process time: 0.36s to process singleimage (processingservice.py:242)
```

**Comment by mgineer85** [comment]
> ```
> 2024-02-07 18:02:32,995 [    INFO] -- process time: 1.59s to create scaled images (processingservice.py:237)
> 2024-02-07 18:02:33,355 [    INFO] -- process time: 0.36s to process singleimage (processingservice.py:242)
> ```

Hehe, ok the turbojpeg implementation is really good 🙂

**Comment by samyness** [comment]
1. I'll try to set the quality lower and check what happens. (Strange that the delay only occurs when the viewfinder is deactivated. Maby the focusing takes to much time, the Imagequality stays the same.)
2. If that doesn't work, I'll try to set the timeout to 10sec. and see what happens. 

Is it normal that "device timed out deliver lores image" during taking hq picture?

**Comment by mgineer85** [comment]
I understood the absolute capture time is about the same with viewfinder enabled/disabled?

You can elongate the timeout, no problem. But it will give a bad user experience with such long times. To compare, on my Canon it takes about 0.5-1seconds until the capture is done.

The lores image deliver timeout is normal. The app keeps asking for the livestream during the capture. When the camera is busy, it should just ignore the requests...
Try to disable liveview and see if the camera behaves better/faster.

**Comment by samyness** [comment]
**I understood the absolute capture time is about the same with viewfinder enabled/disabled?**
No, the capture time is about 3sec. with enabled viewfinder and about 6sec. with disabled viewfinder!

**Try to disable liveview and see if the camera behaves better/faster.**
With disabled liveview the capture takes about 5.5sec.

**Comment by samyness** [comment]
With a 7-second timeout, usually only one photo is taken now. It's rare that the camera triggers twice. 
I'm a bit confused; in the admin settings, I set the Takepic Msg Time to 0.5, but the white screen appears already at a countdown time of 1.3.

**Comment by samyness** [comment]
I have set the retries to 40. Currently, it takes me 5.5 seconds to capture the image."
` def wait_for_lores_image(self, retries: int = 40):` 
in abstractbackend.py

**Comment by mgineer85** [comment]
this prerelease comes with improvements for gphoto2:
- timeout raised from 4s to 8s
- during still capture, the lores stream requests are paused.

https://github.com/photobooth-app/photobooth-app/releases/tag/v2.0a3

**Comment by mgineer85** [comment]
I'm closing this as solved. If you have issues, please reopen.
