### ISSUE TITLE
USB copy does not work on RPI4 ?

### ISSUE THREAD

**Issue by hillerpa** [photobooth-app/photobooth-app#191]
**Describe the bug**
Maybe I'm the idiot but I already renamed my USB to photobooth and created a folder with photobooth.

Other Side effect if I go on Files in the App it is not showing them so there might be a "rights" problem?

**Expected behavior**
expectation would have been that it is automatically copying the pictures if the service is updated but it is not doing it . Do I need to formate it somehow special or something?

**Screenshots**
USB Folder is Empty

**System (please complete the following information):**
 - OS: Raspberry Pi Bookworm 64bit
 - Browser chrome / Firefox
 - Version latest

Thank you for the great work

**Comment by mgineer85** [comment]
Hey,
Right now as per implementation the files are copied one time only when the stick is plugged in.
when you plug in /out you see messages in the logs? 


here is the logic for your reference
https://github.com/photobooth-app/photobooth-app/blob/main/photobooth/services/filtetransferservice.py

**Comment by hillerpa** [comment]
Thank you for the fast response. I used in the past other photobooth which was automatically syncing all X min - got it now at least how it should work but on my side it does not. 
The Log does not show anything in this direction but the USB device is detected by the OS.
Format is FAT32 - I also tried other USB devices but it did not work...

 I also setted up the whole box again now I can at least access all the files and everything else looks fine, beside the filetransfer. I only activated the USB FIle Transfer Service this should be everything in theory?
 
 I found a small other topic where a "gap" is missing on the documentation:
 
![grafik](https://github.com/photobooth-app/photobooth-app/assets/94315369/573fef79-7bf0-43ef-a686-95e686b7bc96)

**Comment by mgineer85** [comment]
If the system detects the stick well it might be that python does not.
Can you try a script running this line in python https://github.com/photobooth-app/photobooth-app/blob/main/photobooth/services/filtetransferservice.py#L80

run with stick attached and removed. There should be a difference.

**Comment by hillerpa** [comment]
maybe the virus is in front of the PC .... but unfortunately I'm not that well with python: 

I created a test.py script with following code
`print('hello')
print (device for device in psutil.disk_partitions(all=False) if "removable" in device.opts)
get_current_removable_media()
@staticmethod
def get_current_removable_media():
 """Returns set of removable drives detected on the computer."""
 print (device for device in psutil.disk_partitions(all=False) if "removable" in device.opts)`

and then started it with `python test.py` 

Terminal gives back:
NameError: name 'psutil' is not defined

Feedback is also `get_current_removable_media is not defined`
Sorry I tried the last 45min to make it anyhow different working...

**Comment by mgineer85** [comment]
please try following code. 

save it as test.py.
run by `python test.py`
if psutil is missing install it by `pip install psutil`
```
import psutil

print("devices filtered for removable:")
print([device for device in psutil.disk_partitions(all=False) if "removable" in device.opts])
print("devices without any filter:")
print([device for device in psutil.disk_partitions(all=False)])

```

**Comment by hillerpa** [comment]
Thank you very much for your patience:

Here is the outcome without and with - so it is detected by Python (sda1):
![grafik](https://github.com/photobooth-app/photobooth-app/assets/94315369/f83f96e0-9985-4e13-9c0c-307e1c81bcec)

so the issue seems somewhere else - as told the service seems not automatically starting in the Box.

- Activated the Filetransfer into photobooth folder
- Created a folder USB Device: Fotobox Folder: photobooth
- Also tried a Devicename Photbooth with Folder photobooth

**Comment by hillerpa** [comment]
It is an USB-Stick  - I tried now 5 different USB sticks I had laying around also the very common.
![grafik](https://github.com/photobooth-app/photobooth-app/assets/94315369/da74801e-a84a-418d-beab-a7d739bfa120)

Not one is detected as removable. 

I also changed the Format between NTFS, exFAT and FAT32 also makes no difference.
I also changed the interface from a USB3 to a USB2 on the Raspberry PI 4

**Comment by mgineer85** [comment]
I see, thank you for testing. I think the underlying system has changed recently in a way that removable is not signaled any more. Maybe we just remove the filter in the future or find a different way.

**Comment by Striker62** [comment]
silly question would it help to name the stick "removable"
is the format relevalt or is extfat ok

**Comment by mgineer85** [comment]
So it seems the underlying system changed in Bookworm a bit and this leads to usb sticks can not detect as those.

Maybe @Peda1996 can help track down the issue and solve it as the original implementation is by Peda1996.

What is your usecase exactly?
Since there are different ways to access the files on the device, I added a short overview to the documentation. Maybe this works for you also:
https://photobooth-app.org/reference/bulktransferfiles/

**Comment by hillerpa** [comment]
For me this is just the easiest way when I use the box on different locations it is not always the same wifi same for SCP.
It is much more easy also to non technical people to use a USB ^^.

**Comment by mgineer85** [comment]
If the box itself is not in any WiFi the Pi could also create a hotspot from which you login and still use the filebrowser. Just another way ;)

**Comment by Peda1996** [comment]
Hey thanks for the Mention, wouldn't have seen this issue otherwise. I think the issue might have to do with the if 
`if "removable" in device.opts` in the filetransferservice.py. Commenting this if statement worked somehow in my development environment.


```
    @staticmethod
    def get_current_removable_media():
        """Returns set of removable drives detected on the  computer."""
        return {
            device
            for device in psutil.disk_partitions(all=False)
            #    if "removable" in device.opts
        }
```

Tested it with my other USB sticks and somehow I only got it working on one? of my USB sticks with this line of code. (Somehow this was the one I used for my booth to transfer files) So removing this one if statement should work.

Will request a PR shortly.

**Comment by mgineer85** [comment]
Patch merged and version 2 released now, close this. If it still not works, please reopen.
