### ISSUE TITLE
Display available parameters for gphoto2 options in settings>backends via request

### ISSUE THREAD

**Issue by PixelAlarm** [photobooth-app/photobooth-app#219]
**Is your feature request related to a problem? Please describe.**
Different camera models have different settings available.
In the settings, it isn't clear, wich settings can be applied for each section.
Problem: Wrong ISO settings will lead to them not being set in the device (and being ignored) or lead to errors.

**Describe the solution you'd like**
The individual settings are retrievable via gphoto2-request. (e.g. for iso: gphoto2 --list-config iso)
The solution would be to have a button beside the gphoto settings (iso, shutter, focusmode) and retrieve the available parameters. They could then be displayed temporarily as overlay.

**Describe alternatives you've considered**
Retrieve options for settings manually via terminal.
Can't be achieved with running Photobooth-app, since backend would be blocked.

**Additional context**
Please contact, if needed.

**Comment by mgineer85** [comment]
Well this one is more complicated than thought.
Cameras can be open or not, services would need to be stopped to probe the backends.

I think this is not worth the work and could be nailed by some CLI scripts one day.
