### ISSUE TITLE
Print via GPIO pushbuton add notification 

### ISSUE THREAD

**Issue by Striker62** [photobooth-app/photobooth-app#234]
my printer is in an other room, when i try to print via GPIO Buton it looks like nothing happened.
When I check the status view I found lots of printing command . ans in my printer I found alot of pictures.

I would be help full if you can provide the same green info as for the the print function in the media view also for GPIO triggered print

**Comment by mgineer85** [comment]
This one is fixed in 2.0.4.
There are notifications triggered regardless if requested via keyboard, gpio or rest api.
