### ISSUE TITLE
editing the translation

### ISSUE THREAD

**Issue by Louloubiwan** [photobooth-app/photobooth-app#245]
Hello, I'm French, and I can see that the translation isn't good. I'm trying to find where the translation file is located because we can't change the text in the photobooth app. So, if you know where we can change the language/translation, it would be helpful. 
Thank you 😉

**Comment by mgineer85** [comment]
Thank you for help improving.
It should be easy for you to translate: https://github.com/photobooth-app/photobooth-app/blob/main/CONTRIBUTING.md#help-translate-the-app
