### ISSUE TITLE
Hiding the gallery delete button is not working

### ISSUE THREAD

**Issue by rektosaure** [photobooth-app/photobooth-app#248]
Hi there,

**Describe the bug**
After taking a photo, the delete button remains visible despite being deselected from the settings.

**To Reproduce**
1. Go to Configuration -> UISettings -> Uncheck "Gallery Show Delete".
2. Take a picture.
3. Delete button remains visible.

**Expected behavior**
The delete button should not be visible to the user if unchecked in the settings.

**System (please complete the following information):**
 - OS: Raspberry Pi Bookworm 64bit
 - Browser: Chromium
 - Version: 2.0.5

**Comment by mgineer85** [comment]
It's okay, it's their photo. If they want to delete they have at least a chance - later in gallery no more...
