### ISSUE TITLE
no log view in the Status screen

### ISSUE THREAD

**Issue by Striker62** [photobooth-app/photobooth-app#249]
Version 2.0.5.

it looks like that the log view in the status screen is no longer working .

I tried Error or Debug level. Nothing shown

**Comment by mgineer85** [comment]
For me it just works. Any errors in browser console? Maybe hit f5 to force a reload?

**Comment by Striker62** [comment]
now it works again. it was an issue with the logging in general. no new entries in the log. after reboot the pi it works

**Comment by mgineer85** [comment]
Maybe if you have the last logfile from when it happend, I can find if there was some errors leading to that behaviour. 
Otherwise good to know it's working again.
