### ISSUE TITLE
Error - when I select a filter

### ISSUE THREAD

**Issue by Louloubiwan** [photobooth-app/photobooth-app#259]
Hello :D
When I try to pick any filter in the dropdownlist, I get this error :

check following fields:
body -> uisettings -> gallery_filter_userselectable -> 0: Input should be 'original', '_1977', 'aden', 'ashby', 'amaro', 'brannan', 'brooklyn', 'charmes', 'clarendon', 'crema', 'dogpatch', 'earlybird', 'gingham', 'ginza', 'hefe', 'helena', 'hudson', 'inkwell', 'juno', 'kelvin', 'lark', 'lofi', 'ludwig', 'maven', 'mayfair', 'moon', 'nashville', 'perpetua', 'poprocket', 'reyes', 'rise', 'sierra', 'skyline', 'slumber', 'stinson', 'sutro', 'toaster', 'valencia', 'walden', 'willow' or 'xpro2'

**To Reproduce**
1. Go to admin -> uisettings.
2. Click on Pic1 Filter Userselectable.
3. Choose any filter.
4. The Error appear.

**Expected behavior**
To enable the filter that I have choosen

**System :'**
 - OS: Raspberry Pi Bookworm 64bit
 - Browser chromium
 - Version 22

**Comment by mgineer85** [comment]
Which app version you used? I think there was an issue in older version. You need to choose at least one value I think.

**Comment by mgineer85** [comment]
new version 2.0.7 is released and should fix it.

**Comment by Louloubiwan** [comment]
Hello, I confirm that it's working, thank you for your fast reply.
Have a nice day
