### ISSUE TITLE
Printing not Working - „GET /api/print/…/0 HTTP/1.1“ 404

### ISSUE THREAD

**Issue by PixelAlarm** [photobooth-app/photobooth-app#260]
**Describe the bug**
Printing Not working on 3.0a2
Log says „GET /api/print/…/0 HTTP/1.1“ 404 

Printing is working via Terminal.

**To Reproduce**
1. setup Printer via cups 
2. Print From Gallery

**Comment by mgineer85** [comment]
The endpoint is slightly different:
http://localhost:8000/api/doc
![image](https://github.com/photobooth-app/photobooth-app/assets/3868450/494729e1-187f-4463-985a-45c047961b70)

**Comment by mgineer85** [comment]
First and second print latest, the third prints specific id.

**Comment by PixelAlarm** [comment]
So the Print Button in Gallery or result screen will lead to an error in newest Versions.

I don‘t Know Anything about the API.

I just want to trigger the Print from the screen.

**Comment by PixelAlarm** [comment]
The full line is:

2024-05-18 16:27:33,828 [    INFO] 127.0.0.1:47404 - "GET /api/print/b357cb2ee31861f3c789be61a0cc01be/0 HTTP/1.1" 404 (httptools_impl.py:481)

**Comment by mgineer85** [comment]
Dang, very correct. Updated in https://github.com/photobooth-app/photobooth-frontend/commit/a8caa659b2f15aa2695d92ce5b806703eae40ab9

Will be fixed in next release.

**Comment by PixelAlarm** [comment]
Any way to fix it manuelly?

I want to use the photobooth today :)

**Comment by mgineer85** [comment]
Maybe not the best idea to use a prerelease version if urgently needed... ;)

I just released a new version, wait until its done and you can update as usual: https://github.com/photobooth-app/photobooth-app/actions/runs/9140662352
