### ISSUE TITLE
How to choose from multiple printer configurations on result screen / gallery

### ISSUE THREAD

**Issue by mgineer85** [photobooth-app/photobooth-app#288]
### Discussed in https://github.com/photobooth-app/photobooth-app/discussions/283

<div type='discussions-op-text'>

<sup>Originally posted by **PixelAlarm** June  4, 2024</sup>
Hi,

Offtopic:
I have a printer that prints 20x15cm. Possible media formats are 1x full-size: 20x15cm or 2x half-size: 10x15cm.

Actual question:
My idea was to have two printer routines: 1x full-size or 2x half-size.
Now I set up two routines, but I cannot choose between configurations on result screen or from gallery.
There is only one button that will use the first configuration.

Is there a way to choose between the routines?</div>

**Comment by mgineer85** [comment]
https://github.com/photobooth-app/photobooth-app/discussions/283#discussioncomment-9689024

**Comment by mgineer85** [comment]
https://github.com/photobooth-app/photobooth-app/issues/276

**Comment by mgineer85** [comment]
![image](https://github.com/photobooth-app/photobooth-app/assets/3868450/9c32bc45-cdc4-404a-8d47-26abbdf35960)
@PixelAlarm @baumrasen Just a mockup, it could look like this

**Comment by PixelAlarm** [comment]
Looking forward to the possibility :)

For my taste it would be nice to have only 1 print/share bottom at the top and if pressed there would be a floating option window with icons and short description of the options. (similar to the bottom menu of front screen)

**Comment by mgineer85** [comment]
Yes, I would like to avoid cluttering the screen too much with distracting stuff.
I think it could be configurable how many items are displayed and which elements are hidden in a dropdown.

**Comment by mgineer85** [comment]
![image](https://github.com/user-attachments/assets/fb4fcff6-c57a-44b1-ba06-8cf40c9b773f)
![image](https://github.com/user-attachments/assets/f72f86a7-8e58-49aa-ab8c-37533c70e1e0)

This feature will be included in next release.
QR share config and printing config will be lost because the config got rearranged - so it will be released as v4 to signal breaking change.

**Comment by mgineer85** [comment]
This will be included in v4 - beta1 is released: https://pypi.org/project/photobooth-app/4.0.0b1/

It's major version change because qrcode share and printing settings will be lost after update :|
