### ISSUE TITLE
Print quantity limitation and usage monitoring

### ISSUE THREAD

**Issue by rektosaure** [photobooth-app/photobooth-app#295]
**Is your feature request related to a problem? Please describe.**
There is currently no built-in functionality to limit the quantity of prints in the system, nor is there an option to display the number of already printed pictures in the gallery area. This lack of functionality can lead to challenges in managing print quantities and monitoring usage, particularly on high-volume printers.

**Describe the solution you'd like**
I propose the implementation of a feature that allows administrators to set limits on the number of prints available and provides an option to display the number of already printed pictures in the gallery area aimed at end users.

**Describe alternatives you've considered**
Bash script as proposed in https://github.com/photobooth-app/photobooth-app/discussions/294 but relying solely on external scripts is not a sustainable long-term approach

**Additional context**
In a high-volume printing environment, the lack of built-in functionality to limit print quantities and monitor usage can significantly impact efficiency and resource management. It is essential to address this gap to better serve users in managing their printing needs effectively.

**Comment by mgineer85** [comment]
While I would consider a print stats counter in the admin dashboard as kind of useful, I myself will not implement a limitation or display in the frontend. High volume printing could indicate a commercial/professional use for which you would need to implement the display to the user and limitation yourself.   I do not think the user would benefit from the display in the gallery anyways because he cannot use the information: If he runs in the limitation the user will just be frustrated. Just let them print...

**Comment by mgineer85** [comment]
I see your points. 
Why would early users get away with many prints and later with no prints?
Could the option to use blocking time be a good alternative? If prints are limited to for example 1 per minute, the waste would be highly reduced.

**Comment by loiczam** [comment]
Hello,

you can add this code into shareservice.py L48 

`max_prints = getattr(appconfig.share, 'maxprint', 0)
        if max_prints > 0 and self._information_service._gather_printing_stats() >= max_prints:
            self._sse_service.dispatch_event(
                SseEventFrontendNotification(
                    color="info",
                    message="Maximum number of impressions reached! Please try again later.",
                    caption="Share Service Error",
                )
            )
            raise RuntimeError("Maximum number of impressions reached!")`

and adding "maxprint": 300, into config.json in "share" section.

If someone can add a field into the admin form to edit maxprint.

**Comment by loiczam** [comment]
Hello,

i push a feature : https://github.com/photobooth-app/photobooth-app/pull/332

![error](https://github.com/user-attachments/assets/bd364ce2-e36d-4a27-869c-ed96ab309233)
![admin](https://github.com/user-attachments/assets/b5ac0c2f-4ea4-4030-97be-cb9af88a92e8)

**Comment by mgineer85** [comment]
It took some effort to get the code right, but it is implemented now.
Thx @loiczam !
