### ISSUE TITLE
Cannot login admin pannel 

### ISSUE THREAD

**Issue by cmoi1000** [photobooth-app/photobooth-app#343]
Hello,
I update from 3.0 to 4.0, and in cannot login in the admin pannel with the default password " 0000 "
I have the following message : failed to authenticate.
I try to login in Chrome private mode : same message.

Someone can help me ?
Thanks !

Yoann

**Comment by mgineer85** [comment]
Could you please restart and maybe clear cache once? Maybe there is something going on…

**Comment by cmoi1000** [comment]
I've reboot another time and clear the cache instead private mode.
It's working sorry for the useless question ...
Thanks a lot !
