### ISSUE TITLE
No print button

### ISSUE THREAD

**Issue by Louloubiwan** [photobooth-app/photobooth-app#345]
**Describe the bug**
![IMG_20240823_182957.jpg](https://github.com/user-attachments/assets/abe53e97-065f-4f37-b59d-ef7daafa8764)

Hello, so there is no print button when photo taken even with the Show print true. If you know how to fix it, thank you !
 [IMG_20240823_183321.jpg](https://github.com/user-attachments/assets/eb141c3b-7b39-4f98-bf80-1b53c6a83255)

**To Reproduce**
Take a photo and try to print it

 - Raspberry Pi Bookworm 64bit
 - Chromium
 - Version : the last one

**Comment by Striker62** [comment]
Hi, you can check in the share section of the config 

Number Direct Access Buttons
Number of buttons directly accessible in the gallery. Remaining items are available in the more-menu.

Does this fit with the no of buttons ?
If Yes it cloud be a browser cache problem.

**Comment by mgineer85** [comment]
Yes could be cache or after update there is no new default share option configured. Go to the share actions and ensure there is one.

Also ensure the global switch share-enable is active in that section.
