### ISSUE TITLE
Stream error after updating Bookworm

### ISSUE THREAD

**Issue by WebfinityDesign** [photobooth-app/photobooth-app#357]
I get "Oh no, Stream error" after updating Bookworm with apt update && apt upgrade.
There is no way to access the camera anymore.
I'm using the Arducam Hawkeye 64MP.

Can anyone get me in the right direction to solve this?

**Comment by mgineer85** [comment]
Probably you need to reinstall their driver again as if it is new. Good luck.🍀

**Comment by WebfinityDesign** [comment]
That solved it. Thank you!
