### ISSUE TITLE
Api call show error but worked

### ISSUE THREAD

**Issue by Striker62** [photobooth-app/photobooth-app#359]
I'm not sure if it is bug but I try to explain what happend.

I defined a share action to change the frame and take a picture :
the following command is there defined and assigned to the charater "w"

cp /home/pi/photobooth/userdata/frames/wedding.png /home/pi/photobooth/userdata/frames/frame.png && curl -X 'GET' \\ 'http://raspi-photobooth-mini:8000/api/actions/image/0' \\ -H 'accept: application/json

If Ipress "w"
the command work the frame copy worked and the picture was taken.

For me perfect;-)

But I get the following error in the log and on the main screen

ERROR
30.Sep.24 18:15:13	HTTPException: HTTPException(status_code=500, detail="Something went wrong, Exception: Process failed, error Command 'cp /home/pi/photobooth/userdata/frames/wedding.png /home/pi/photobooth/userdata/frames/frame.png && curl -X 'GET' \\ 'http://raspi-photobooth-mini:8000/api/actions/image/0' \\ -H 'accept: application/json' ' returned non-zero exit status 3.")

**Comment by mgineer85** [comment]
I am not very sure how chained commands work in linux. cp / curl seem to work, but maybe it's something about the link &&?

**Comment by Striker62** [comment]
i tried also only
curl -X 'GET' \   'http://raspi-photobooth-mini:8000/api/actions/image/0' \   -H 'accept: application/json' 
same result ?

**Comment by Striker62** [comment]
ok found the issue the correct call is
curl -X GET http://raspi-photobooth-mini:8000/api/actions/image/0 -H 'accept: application/json'
that works without error

**Comment by mgineer85** [comment]
Here is the exit codes overview: https://everything.curl.dev/cmdline/exitcode.html

**Comment by Striker62** [comment]
thanks . That is where I found the solution
