### ISSUE TITLE
No livestreams outside the action shows

### ISSUE THREAD

**Issue by cedric-Swiss** [photobooth-app/photobooth-app#367]
**Is your feature request related to a problem? Please describe.**
Is it possible to activate an image for the basic screen of the application, instead of the liveview, and only activate the liveview, when an action (Photo or collage) is triggered?

**Describe the solution you'd like**
I'd like to be able to display an image on the Photobooth screen, and when an action is triggered, only display the livestream.

**Comment by PixelAlarm** [comment]
I use the box the same way. Have a welcome screen and only show the live view when a button is pressed.

My workaround:
1. Place a filename.png inside the web_spa folder.
2. Use this .png as welcome message. For this put this inside the welcome text field in UI settings <img src=„filename.png“> (keep the styling information as fixed-center etc…

**Comment by mgineer85** [comment]
Hey, upcoming version 5 has this feature. 

![image](https://github.com/user-attachments/assets/01399cd9-16cc-4f34-9121-f2b04a0729aa)

**Comment by PixelAlarm** [comment]
Looking forward to this feature, although for me my workaround is doing well.

Just wondering: What will be displayed, when livestream is disabled?
Will there be some option to define a local image file to be displayed?
Could also be nice to use png as frame/overlay etc.

**Comment by mgineer85** [comment]
Right now it would just show the frontend ui text defined. This could be used to display a frame also but is not very intuitive and needs improvement in the future I think.
