### ISSUE TITLE
Use opencv-python-headless instead of opencv-python

### ISSUE THREAD

**Issue by mako2580** [photobooth-app/photobooth-app#368]
Since you are not using OpenCV for any GUI tasks, I think it would be sufficient to use only `opencv-python-headless` package, which is stripped version from all GUI related things.

**Comment by mgineer85** [comment]
Well during dev it was used from time to time but I do not see any reason not to switch to headless.

what is the reason you would prefer headless?
I would assume it’s installed on systems with gui/display anyways and the dependencies are already there?

**Comment by mgineer85** [comment]
There is an updated release using headless cv: https://github.com/photobooth-app/photobooth-app/releases/tag/v4.1.0
