### ISSUE TITLE
Customize UI

### ISSUE THREAD

**Issue by mgineer85** [photobooth-app/photobooth-app#86]
- [x] custom colors https://quasar.dev/style/color-palette#dynamic-change-of-brand-colors-dynamic-theme-colors-
- [x] custom fonts https://quasar.dev/style/typography
- [x] translations https://quasar.dev/options/app-internationalization
- [x] add private user css so display can be modded, https://github.com/photobooth-app/photobooth-app/discussions/171

**Comment by DominicWindisch** [comment]
Regarding user css, do you plan on allowing a user provided css stylesheet or to add css to specific components? 

In the dev branch of my fork, I've added user css to some components ([action buttons](https://github.com/DominicWindisch/photobooth-frontend/blob/54a1a9675d3756f466554a48eebd550b0e331004/src/pages/IndexPage.vue#L41), gallery button, toolbar), but that quickly gets out of hand with an input for each tiny component... On the other hand, to make a user stylesheet more accessible, we should at least add IDs to some of the core components.

**Comment by mgineer85** [comment]
Jeah Right.
I would love to allow the user upload a file to a userdata folder. The folder shall not be deleted during updates. Also a custom i18n file might be possible, if some very specific language shall be used.
Not sure yet what the simplest way is to load additional files in ui if avail from server…
